server:
  port: 9090
  ssl:
    client-auth:

spring:
  datasource:
    url: jdbc:h2:mem:custs-db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
    path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/till_realm
          jwt-set-uri: http://localhost:8080/realms/till_realm/protocol/openid-connect/certs
authorization:
  url: http://localhost:8080/realms/till_realm/protocol/openid-connect/token